// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/user/handler/grpc/login_grpc_handler.proto

package grpc_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcHandlerClient is the client API for GrpcHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcHandlerClient interface {
	LoginHandler(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type grpcHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcHandlerClient(cc grpc.ClientConnInterface) GrpcHandlerClient {
	return &grpcHandlerClient{cc}
}

func (c *grpcHandlerClient) LoginHandler(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/grpc_handler.GrpcHandler/LoginHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcHandlerServer is the server API for GrpcHandler service.
// All implementations must embed UnimplementedGrpcHandlerServer
// for forward compatibility
type GrpcHandlerServer interface {
	LoginHandler(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedGrpcHandlerServer()
}

// UnimplementedGrpcHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcHandlerServer struct {
}

func (UnimplementedGrpcHandlerServer) LoginHandler(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginHandler not implemented")
}
func (UnimplementedGrpcHandlerServer) mustEmbedUnimplementedGrpcHandlerServer() {}

// UnsafeGrpcHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcHandlerServer will
// result in compilation errors.
type UnsafeGrpcHandlerServer interface {
	mustEmbedUnimplementedGrpcHandlerServer()
}

func RegisterGrpcHandlerServer(s grpc.ServiceRegistrar, srv GrpcHandlerServer) {
	s.RegisterService(&GrpcHandler_ServiceDesc, srv)
}

func _GrpcHandler_LoginHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHandlerServer).LoginHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_handler.GrpcHandler/LoginHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHandlerServer).LoginHandler(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcHandler_ServiceDesc is the grpc.ServiceDesc for GrpcHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_handler.GrpcHandler",
	HandlerType: (*GrpcHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginHandler",
			Handler:    _GrpcHandler_LoginHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/user/handler/grpc/login_grpc_handler.proto",
}
