// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: internal/order/handler/grpc/order_grpc_handler.proto

package grpc_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string              `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Limit  int32               `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset int32               `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Filter *OrderRequestFilter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OrderRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *OrderRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *OrderRequest) GetFilter() *OrderRequestFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type OrderRequestFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId int32  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Offset int32  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Phone  string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Status string `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Start  int64  `protobuf:"varint,6,opt,name=Start,proto3" json:"Start,omitempty"`
	End    int64  `protobuf:"varint,7,opt,name=End,proto3" json:"End,omitempty"`
}

func (x *OrderRequestFilter) Reset() {
	*x = OrderRequestFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequestFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequestFilter) ProtoMessage() {}

func (x *OrderRequestFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequestFilter.ProtoReflect.Descriptor instead.
func (*OrderRequestFilter) Descriptor() ([]byte, []int) {
	return file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescGZIP(), []int{1}
}

func (x *OrderRequestFilter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRequestFilter) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRequestFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *OrderRequestFilter) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderRequestFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderRequestFilter) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *OrderRequestFilter) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type OrderItemSkuJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item_Id   int32   `protobuf:"varint,1,opt,name=Item_Id,json=ItemId,proto3" json:"Item_Id,omitempty"`
	SkuId     int32   `protobuf:"varint,2,opt,name=SkuId,proto3" json:"SkuId,omitempty"`
	SkuName   string  `protobuf:"bytes,3,opt,name=SkuName,proto3" json:"SkuName,omitempty"`
	Quantity  int32   `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Price     float32 `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Subtotal  float32 `protobuf:"fixed32,6,opt,name=Subtotal,proto3" json:"Subtotal,omitempty"`
	SmallName string  `protobuf:"bytes,7,opt,name=SmallName,proto3" json:"SmallName,omitempty"`
}

func (x *OrderItemSkuJson) Reset() {
	*x = OrderItemSkuJson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemSkuJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemSkuJson) ProtoMessage() {}

func (x *OrderItemSkuJson) ProtoReflect() protoreflect.Message {
	mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemSkuJson.ProtoReflect.Descriptor instead.
func (*OrderItemSkuJson) Descriptor() ([]byte, []int) {
	return file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemSkuJson) GetItem_Id() int32 {
	if x != nil {
		return x.Item_Id
	}
	return 0
}

func (x *OrderItemSkuJson) GetSkuId() int32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *OrderItemSkuJson) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *OrderItemSkuJson) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemSkuJson) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemSkuJson) GetSubtotal() float32 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *OrderItemSkuJson) GetSmallName() string {
	if x != nil {
		return x.SmallName
	}
	return ""
}

type OrdersJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string              `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId     string              `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Address    string              `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone      string              `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Comment    string              `protobuf:"bytes,5,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Status     string              `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	CreateTs   string              `protobuf:"bytes,7,opt,name=Create_ts,json=CreateTs,proto3" json:"Create_ts,omitempty"`
	OrderItems []*OrderItemSkuJson `protobuf:"bytes,8,rep,name=orderItems,proto3" json:"orderItems,omitempty"`
	Total_Sum  string              `protobuf:"bytes,9,opt,name=Total_Sum,json=TotalSum,proto3" json:"Total_Sum,omitempty"`
}

func (x *OrdersJson) Reset() {
	*x = OrdersJson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdersJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersJson) ProtoMessage() {}

func (x *OrdersJson) ProtoReflect() protoreflect.Message {
	mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersJson.ProtoReflect.Descriptor instead.
func (*OrdersJson) Descriptor() ([]byte, []int) {
	return file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescGZIP(), []int{3}
}

func (x *OrdersJson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrdersJson) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrdersJson) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrdersJson) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrdersJson) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OrdersJson) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrdersJson) GetCreateTs() string {
	if x != nil {
		return x.CreateTs
	}
	return ""
}

func (x *OrdersJson) GetOrderItems() []*OrderItemSkuJson {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *OrdersJson) GetTotal_Sum() string {
	if x != nil {
		return x.Total_Sum
	}
	return ""
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdersJson []*OrdersJson `protobuf:"bytes,1,rep,name=ordersJson,proto3" json:"ordersJson,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescGZIP(), []int{4}
}

func (x *OrderResponse) GetOrdersJson() []*OrdersJson {
	if x != nil {
		return x.OrdersJson
	}
	return nil
}

var File_internal_order_handler_grpc_order_grpc_handler_proto protoreflect.FileDescriptor

var file_internal_order_handler_grpc_order_grpc_handler_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x45, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x6e, 0x64,
	0x22, 0xc7, 0x01, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x6b,
	0x75, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x53, 0x6b, 0x75, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53,
	0x6b, 0x75, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x53, 0x75, 0x62, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x90, 0x02, 0x0a, 0x0a, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x73,
	0x12, 0x3e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x6b, 0x75,
	0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x53, 0x75, 0x6d, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x6d, 0x22, 0x49, 0x0a,
	0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x32, 0x56, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x15, 0x5a, 0x13, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescOnce sync.Once
	file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescData = file_internal_order_handler_grpc_order_grpc_handler_proto_rawDesc
)

func file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescGZIP() []byte {
	file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescOnce.Do(func() {
		file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescData)
	})
	return file_internal_order_handler_grpc_order_grpc_handler_proto_rawDescData
}

var file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_order_handler_grpc_order_grpc_handler_proto_goTypes = []interface{}{
	(*OrderRequest)(nil),       // 0: grpc_handler.OrderRequest
	(*OrderRequestFilter)(nil), // 1: grpc_handler.OrderRequestFilter
	(*OrderItemSkuJson)(nil),   // 2: grpc_handler.OrderItemSkuJson
	(*OrdersJson)(nil),         // 3: grpc_handler.OrdersJson
	(*OrderResponse)(nil),      // 4: grpc_handler.OrderResponse
}
var file_internal_order_handler_grpc_order_grpc_handler_proto_depIdxs = []int32{
	1, // 0: grpc_handler.OrderRequest.filter:type_name -> grpc_handler.OrderRequestFilter
	2, // 1: grpc_handler.OrdersJson.orderItems:type_name -> grpc_handler.OrderItemSkuJson
	3, // 2: grpc_handler.OrderResponse.ordersJson:type_name -> grpc_handler.OrdersJson
	0, // 3: grpc_handler.OrderHandler.OrderList:input_type -> grpc_handler.OrderRequest
	4, // 4: grpc_handler.OrderHandler.OrderList:output_type -> grpc_handler.OrderResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_order_handler_grpc_order_grpc_handler_proto_init() }
func file_internal_order_handler_grpc_order_grpc_handler_proto_init() {
	if File_internal_order_handler_grpc_order_grpc_handler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequestFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemSkuJson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdersJson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_order_handler_grpc_order_grpc_handler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_order_handler_grpc_order_grpc_handler_proto_goTypes,
		DependencyIndexes: file_internal_order_handler_grpc_order_grpc_handler_proto_depIdxs,
		MessageInfos:      file_internal_order_handler_grpc_order_grpc_handler_proto_msgTypes,
	}.Build()
	File_internal_order_handler_grpc_order_grpc_handler_proto = out.File
	file_internal_order_handler_grpc_order_grpc_handler_proto_rawDesc = nil
	file_internal_order_handler_grpc_order_grpc_handler_proto_goTypes = nil
	file_internal_order_handler_grpc_order_grpc_handler_proto_depIdxs = nil
}
